version: '3.8'

services:
  app:
    build: .
    container_name: dash_app
    ports:
      - "8050:8050"
    environment:
      - POSTGRES_USER=vizov
      - POSTGRES_PASSWORD=vizov
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: vizov
      POSTGRES_PASSWORD: vizov
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
